import { Schema } from 'mongoose';

export const CircuitSchema = new Schema(
  {
    idCircuit: { type: String, required: true, unique: true },
    idEspn: { type: String, default: '' },
    idTsdb: { type: String, default: '' },
    idMss: { type: String, default: '' },
    idMyL: { type: String, default: '' },
    idRCtrl: { type: String, default: '' },
    strCircuit: { type: String, default: '' },
    strCircuitShort: { type: String, default: '' },
    strAlternate: { type: String, default: '' },
    intFormedYear: { type: String, default: '' },
    strSport: { type: String, default: '' },
    strLeague: { type: String, default: '' },
    strType: { type: String, default: '' },
    strLength: { type: String, default: '' },
    strDirection: { type: String, default: '' },
    strCorners: { type: String, default: '' },
    strRSS: { type: String, default: '' },
    strStadium: { type: String, default: '' },
    strStadiumThumb: { type: String, default: '' },
    strStadiumDescription: { type: String, default: '' },
    strStadiumLocation: { type: String, default: '' },
    intStadiumCapacity: { type: String, default: '' },
    intSoccerXMLTeamID: { type: String, default: '' },
    numSeason: { type: Number, default: new Date().getFullYear() },
    strWebsite: { type: String, default: '' },
    strFacebook: { type: String, default: '' },
    strTwitter: { type: String, default: '' },
    strInstagram: { type: String, default: '' },
    strYoutube: { type: String, default: '' },
    strDescriptionEN: { type: String, default: '' },
    strDescriptionDE: { type: String, default: '' },
    strDescriptionFR: { type: String, default: '' },
    strDescriptionCN: { type: String, default: '' },
    strDescriptionIT: { type: String, default: '' },
    strDescriptionJP: { type: String, default: '' },
    strDescriptionRU: { type: String, default: '' },
    strDescriptionES: { type: String, default: '' },
    strDescriptionPT: { type: String, default: '' },
    strDescriptionSE: { type: String, default: '' },
    strDescriptionNL: { type: String, default: '' },
    strDescriptionHU: { type: String, default: '' },
    strDescriptionNO: { type: String, default: '' },
    strDescriptionIL: { type: String, default: '' },
    strDescriptionPL: { type: String, default: '' },
    strAddress: { type: String, default: '' },
    strCountry: { type: String, default: '' },
    strBadge: { type: String, default: '' },
    strJersey: { type: String, default: '' },
    strLogo: { type: String, default: '' },
    strFanart1: { type: String, default: '' },
    strFanart2: { type: String, default: '' },
    strFanart3: { type: String, default: '' },
    strFanart4: { type: String, default: '' },
    strBanner: { type: String, default: '' },
    strLocked: { type: String, default: '' },
    isOnlyImg: { type: Boolean, default: false },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
