import { Schema } from 'mongoose';

export const DriverSchema = new Schema(
  {
    idPlayer: { type: String, required: true, unique: true },
    idOrg: { type: Schema.Types.ObjectId, ref: 'Orgs', required: true },
    idCat: { type: Schema.Types.ObjectId, ref: 'Cats', required: true },
    idTeam: { type: Schema.Types.ObjectId, ref: 'Teams' },
    idTeam2: { type: Schema.Types.ObjectId, ref: 'Teams' },
    idTeamNational: { type: String, default: '' },
    idEspn: { type: String, default: '' },
    idTsdb: { type: String, default: '' },
    idMss: { type: String, default: '' },
    idMyL: { type: String, default: '' },
    idRCtrl: { type: String, default: '' },
    idSoccerXML: { type: String, default: '' },
    idAPIfootball: { type: String, default: '' },
    idPlayerManager: { type: String, default: '' },
    strNationality: { type: String, default: '' },
    strPlayer: { type: String, required: true },
    strTeam: { type: String, default: '' },
    strTeam2: { type: String, default: '' },
    strSport: { type: String, default: '' },
    intSoccerXMLTeamID: { type: String, default: '' },
    dateBorn: { type: String, default: '' },
    strNumber: { type: String, default: '' },
    dateSigned: { type: String, default: '' },
    strSigning: { type: String, default: '' },
    strWage: { type: String, default: '' },
    strOutfitter: { type: String, default: '' },
    strKit: { type: String, default: '' },
    strAgent: { type: String, default: '' },
    strBirthLocation: { type: String, default: '' },
    strDescriptionEN: { type: String, default: '' },
    strDescriptionDE: { type: String, default: '' },
    strDescriptionFR: { type: String, default: '' },
    strDescriptionCN: { type: String, default: '' },
    strDescriptionIT: { type: String, default: '' },
    strDescriptionJP: { type: String, default: '' },
    strDescriptionRU: { type: String, default: '' },
    strDescriptionES: { type: String, default: '' },
    strDescriptionPT: { type: String, default: '' },
    strDescriptionSE: { type: String, default: '' },
    strDescriptionNL: { type: String, default: '' },
    strDescriptionHU: { type: String, default: '' },
    strDescriptionNO: { type: String, default: '' },
    strDescriptionIL: { type: String, default: '' },
    strDescriptionPL: { type: String, default: '' },
    strGender: { type: String, default: '' },
    strSide: { type: String, default: '' },
    strPosition: { type: String, default: '' },
    strCollege: { type: String, default: '' },
    strFacebook: { type: String, default: '' },
    strWebsite: { type: String, default: '' },
    strTwitter: { type: String, default: '' },
    strInstagram: { type: String, default: '' },
    strYoutube: { type: String, default: '' },
    strHeight: { type: String, default: '' },
    strWeight: { type: String, default: '' },
    intLoved: { type: String, default: '' },
    strThumb: { type: String, default: '' },
    strCutout: { type: String, default: '' },
    strRender: { type: String, default: '' },
    strBanner: { type: String, default: '' },
    strFanart1: { type: String, default: '' },
    strFanart2: { type: String, default: '' },
    strFanart3: { type: String, default: '' },
    strFanart4: { type: String, default: '' },
    strCreativeCommons: { type: String, default: '' },
    strLocked: { type: String, default: '' },
    isOnlyImg: { type: Boolean, default: false },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
