import { Document } from 'mongoose';
import { IOrg } from '../../org/interfaces';
import { BaseInterface } from '../../../shared/base.interface';
import { ITeam } from '../../team/interfaces';
import { ICat } from '../../cat/interfaces';

export interface IDriver extends Document, BaseInterface {
  readonly idPlayer: string;
  readonly idLeague: IOrg;
  readonly idCategory: ICat;
  readonly idTeam: ITeam;
  readonly idTeam2: ITeam;
  readonly idTeamNational: string;
  readonly idEspn: string;
  readonly idTsdb: string;
  readonly idMss: string;
  readonly idRCtrl: string;
  readonly idSoccerXML: string;
  readonly idAPIfootball: string;
  readonly idPlayerManager: string;
  readonly strNationality: string;
  readonly strPlayer: string;
  readonly strTeam: string;
  readonly strTeam2: string;
  readonly strSport: string;
  readonly intSoccerXMLTeamID: string;
  readonly dateBorn: string;
  readonly strNumber: string;
  readonly dateSigned: string;
  readonly strSigning: string;
  readonly strWage: string;
  readonly strOutfitter: string;
  readonly strKit: string;
  readonly strAgent: string;
  readonly strBirthLocation: string;
  readonly strDescriptionEN: string;
  readonly strDescriptionDE: string;
  readonly strDescriptionFR: string;
  readonly strDescriptionCN: string;
  readonly strDescriptionIT: string;
  readonly strDescriptionJP: string;
  readonly strDescriptionRU: string;
  readonly strDescriptionES: string;
  readonly strDescriptionPT: string;
  readonly strDescriptionSE: string;
  readonly strDescriptionNL: string;
  readonly strDescriptionHU: string;
  readonly strDescriptionNO: string;
  readonly strDescriptionIL: string;
  readonly strDescriptionPL: string;
  readonly strGender: string;
  readonly strSide: string;
  readonly strPosition: string;
  readonly strCollege: string;
  readonly strFacebook: string;
  readonly strWebsite: string;
  readonly strTwitter: string;
  readonly strInstagram: string;
  readonly strYoutube: string;
  readonly strHeight: string;
  readonly strWeight: string;
  readonly intLoved: string;
  readonly strThumb: string;
  readonly strCutout: string;
  readonly strRender: string;
  readonly strBanner: string;
  readonly strFanart1: string;
  readonly strFanart2: string;
  readonly strFanart3: string;
  readonly strFanart4: string;
  readonly strCreativeCommons: string;
  readonly strLocked: string;
  readonly isOnlyImg: boolean;
}
