import { Schema } from 'mongoose';

export const CatSchema = new Schema(
  {
    idCategory: { type: String, required: true, unique: true },
    idOrg: { type: Schema.Types.ObjectId, ref: 'Orgs', required: true },
    idLeague: { type: String, required: true },
    strCat: { type: String, required: true },
    strCatShort: String,
    strAlternate: String,
    idEspn: String,
    idTsdb: String,
    idMss: String,
    idMyL: String,
    idRCtrl: String,
    intFormedYear: String,
    strSport: String,
    strLeague: String,
    strDivision: String,
    strManager: String,
    strWebsite: String,
    strFacebook: String,
    strTwitter: String,
    strInstagram: String,
    strDescriptionEN: String,
    strDescriptionDE: String,
    strDescriptionFR: String,
    strDescriptionCN: String,
    strDescriptionIT: String,
    strDescriptionJP: String,
    strDescriptionRU: String,
    strDescriptionES: String,
    strDescriptionPT: String,
    strDescriptionSE: String,
    strDescriptionNL: String,
    strDescriptionHU: String,
    strDescriptionNO: String,
    strDescriptionIL: String,
    strDescriptionPL: String,
    strCountry: String,
    strBadge: String,
    strJersey: String,
    strLogo: String,
    strFanart1: String,
    strFanart2: String,
    strFanart3: String,
    strFanart4: String,
    strBanner: String,
    strYoutube: String,
    strLocked: String,
    rank: { type: Number, default: 999 },
    infoInCat: { type: Boolean, default: false },
    isOnlyImg: { type: Boolean, default: false },
    isWorking: { type: Boolean, default: true },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
