import { Document } from 'mongoose';
import { IOrg } from '../../org/interfaces';
import { BaseInterface } from '../../../shared/base.interface';
import { ICat } from '../../cat/interfaces';

export interface ITeam extends Document, BaseInterface {
  readonly idTeam: string;
  idOrg: string;
  idCat: string;
  readonly idEspn: string;
  readonly idTsdb: string;
  readonly idMss: string;
  readonly idMyL: string;
  readonly idRCtrl: string;
  readonly idSoccerXML: string;
  readonly idAPIfootball: string;
  readonly intLoved: string;
  readonly strTeam: string;
  readonly strTeamShort: string;
  readonly strAlternate: string;
  readonly intFormedYear: string;
  readonly strSport: string;
  readonly strLeague: string;
  readonly strLeague2: string;
  readonly idLeague2: IOrg;
  readonly strLeague3: string;
  readonly idLeague3: IOrg;
  readonly strLeague4: string;
  readonly idLeague4: IOrg;
  readonly strLeague5: string;
  readonly idLeague5: IOrg;
  readonly strLeague6: string;
  readonly idLeague6: IOrg;
  readonly strLeague7: string;
  readonly idLeague7: IOrg;
  readonly strDivision: string;
  readonly strManager: string;
  readonly strStadium: string;
  readonly strKeywords: string;
  readonly strRSS: string;
  readonly strStadiumThumb: string;
  readonly strStadiumDescription: string;
  readonly strStadiumLocation: string;
  readonly intStadiumCapacity: string;
  readonly numSeason: number;
  readonly strWebsite: string;
  readonly strFacebook: string;
  readonly strTwitter: string;
  readonly strInstagram: string;
  readonly strYoutube: string;
  readonly strDescriptionEN: string;
  readonly strDescriptionDE: string;
  readonly strDescriptionFR: string;
  readonly strDescriptionCN: string;
  readonly strDescriptionIT: string;
  readonly strDescriptionJP: string;
  readonly strDescriptionRU: string;
  readonly strDescriptionES: string;
  readonly strDescriptionPT: string;
  readonly strDescriptionSE: string;
  readonly strDescriptionNL: string;
  readonly strDescriptionHU: string;
  readonly strDescriptionNO: string;
  readonly strDescriptionIL: string;
  readonly strDescriptionPL: string;
  readonly strGender: string;
  readonly strCountry: string;
  readonly strTeamBadge: string;
  readonly strTeamJersey: string;
  readonly strTeamLogo: string;
  readonly strTeamFanart1: string;
  readonly strTeamFanart2: string;
  readonly strTeamFanart3: string;
  readonly strTeamFanart4: string;
  readonly strTeamBanner: string;
  readonly strLocked: string;
  readonly isOnlyImg: boolean;
}
