import { Schema } from 'mongoose';

export const OrgSchema = new Schema(
  {
    idLeague: { type: String, required: true, unique: true },
    strLeague: { type: String, required: true },
    strLeagueAlternate: String,
    alias: String,
    categories: [{ type: Schema.Types.ObjectId, ref: 'Cats' }],
    idEspn: String,
    idTsdb: String,
    idMss: String,
    idMyL: String,
    idRCtrl: String,
    intFormedYear: String,
    strCurrentSeason: String,
    strCountry: String,
    strWebsite: String,
    strFacebook: String,
    strTwitter: String,
    strYoutube: String,
    strInstagram: String,
    strDescriptionEN: String,
    strDescriptionDE: String,
    strDescriptionFR: String,
    strDescriptionIT: String,
    strDescriptionCN: String,
    strDescriptionJP: String,
    strDescriptionRU: String,
    strDescriptionES: String,
    strDescriptionPT: String,
    strDescriptionSE: String,
    strDescriptionNL: String,
    strDescriptionHU: String,
    strDescriptionNO: String,
    strDescriptionPL: String,
    strDescriptionIL: String,
    strFanart1: String,
    strFanart2: String,
    strFanart3: String,
    strFanart4: String,
    strBanner: String,
    strBadge: String,
    strLogo: String,
    strPoster: String,
    strTrophy: String,
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
