import { Schema } from 'mongoose';

export const OrgSchema = new Schema(
  {
    idLeague: { type: String, required: true, unique: true },
    strLeague: { type: String, required: true },
    strLeagueAlternate: { type: String, default: '' },
    alias: { type: String, default: '' },
    categories: [{ type: Schema.Types.ObjectId, ref: 'Cats' }],
    strSection: { type: String, default: '' },
    idEspn: { type: String, default: '' },
    idTsdb: { type: String, default: '' },
    idMss: { type: String, default: '' },
    idMyL: { type: String, default: '' },
    idRCtrl: { type: String, default: '' },
    intFormedYear: { type: String, default: '' },
    strCurrentSeason: { type: String, default: '' },
    strCountry: { type: String, default: '' },
    strWebsite: { type: String, default: '' },
    strFacebook: { type: String, default: '' },
    strTwitter: { type: String, default: '' },
    strYoutube: { type: String, default: '' },
    strInstagram: { type: String, default: '' },
    strDescriptionEN: { type: String, default: '' },
    strDescriptionDE: { type: String, default: '' },
    strDescriptionFR: { type: String, default: '' },
    strDescriptionIT: { type: String, default: '' },
    strDescriptionCN: { type: String, default: '' },
    strDescriptionJP: { type: String, default: '' },
    strDescriptionRU: { type: String, default: '' },
    strDescriptionES: { type: String, default: '' },
    strDescriptionPT: { type: String, default: '' },
    strDescriptionSE: { type: String, default: '' },
    strDescriptionNL: { type: String, default: '' },
    strDescriptionHU: { type: String, default: '' },
    strDescriptionNO: { type: String, default: '' },
    strDescriptionPL: { type: String, default: '' },
    strDescriptionIL: { type: String, default: '' },
    strFanart1: { type: String, default: '' },
    strFanart2: { type: String, default: '' },
    strFanart3: { type: String, default: '' },
    strFanart4: { type: String, default: '' },
    strBanner: { type: String, default: '' },
    strBadge: { type: String, default: '' },
    strLogo: { type: String, default: '' },
    strPoster: { type: String, default: '' },
    strTrophy: { type: String, default: '' },
    rank: { type: Number, default: 999 },
    isWorking: { type: Boolean, default: true },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
