import { Document } from 'mongoose';
import { BaseInterface } from '../../../shared/base.interface';

export interface ICat extends Document, BaseInterface {
  readonly idLeague: string;
  idOrg: string;
  readonly idEspn: string;
  readonly idTsdb: string;
  readonly idMss: string;
  readonly idMyL: string;
  readonly idRCtrl: string;
  readonly strLeague: string;
  readonly strLeagueShort: string;
  readonly strLeagueAlternate: string;
  readonly idSoccerXML: string;
  readonly idAPIfootball: string;
  readonly strSport: string;
  readonly strDivision: string;
  readonly idCup: string;
  readonly strCurrentSeason: string;
  readonly intFormedYear: string;
  readonly strGender: string;
  readonly strCountry: string;
  readonly strWebsite: string;
  readonly strFacebook: string;
  readonly strTwitter: string;
  readonly strInstagram: string;
  readonly strYoutube: string;
  readonly strRSS: string;
  readonly strDescriptionEN: string;
  readonly strDescriptionDE: string;
  readonly strDescriptionFR: string;
  readonly strDescriptionCN: string;
  readonly strDescriptionIT: string;
  readonly strDescriptionJP: string;
  readonly strDescriptionRU: string;
  readonly strDescriptionES: string;
  readonly strDescriptionPT: string;
  readonly strDescriptionSE: string;
  readonly strDescriptionNL: string;
  readonly strDescriptionHU: string;
  readonly strDescriptionNO: string;
  readonly strDescriptionIL: string;
  readonly strDescriptionPL: string;
  readonly strFanart1: string;
  readonly strFanart2: string;
  readonly strFanart3: string;
  readonly strFanart4: string;
  readonly strBanner: string;
  readonly strBadge: string;
  readonly strLogo: string;
  readonly strPoster: string;
  readonly strTrophy: string;
  readonly strNaming: string;
  readonly strComplete: string;
  readonly strLocked: string;
  readonly rank: number;
  readonly chYearIni: number;
  readonly chYearFin: number;
  readonly evYearIni: number;
  readonly evYearFin: number;
  readonly infoInCat: boolean;
  readonly isOnlyImg: boolean;
  readonly isWorking: boolean;
}
