import { Document } from 'mongoose';
import { BaseInterface } from '../../../shared/base.interface';

export interface ICat extends Document, BaseInterface {
  readonly idCategory: string;
  idOrg: string;
  readonly idLeague: string;
  readonly strCat: string;
  readonly strCatShort: string;
  readonly idEspn: string;
  readonly idTsdb: string;
  readonly idMss: string;
  readonly idMyL: string;
  readonly idRCtrl: string;
  readonly strAlternate: string;
  readonly intFormedYear: string;
  readonly strSport: string;
  readonly strLeague: string;
  readonly strDivision: string;
  readonly strManager: string;
  readonly strWebsite: string;
  readonly strFacebook: string;
  readonly strTwitter: string;
  readonly strInstagram: string;
  readonly strDescriptionEN: string;
  readonly strDescriptionDE: string;
  readonly strDescriptionFR: string;
  readonly strDescriptionCN: string;
  readonly strDescriptionIT: string;
  readonly strDescriptionJP: string;
  readonly strDescriptionRU: string;
  readonly strDescriptionES: string;
  readonly strDescriptionPT: string;
  readonly strDescriptionSE: string;
  readonly strDescriptionNL: string;
  readonly strDescriptionHU: string;
  readonly strDescriptionNO: string;
  readonly strDescriptionIL: string;
  readonly strDescriptionPL: string;
  readonly strCountry: string;
  readonly strBadge: string;
  readonly strJersey: string;
  readonly strLogo: string;
  readonly strFanart1: string;
  readonly strFanart2: string;
  readonly strFanart3: string;
  readonly strFanart4: string;
  readonly strBanner: string;
  readonly strYoutube: string;
  readonly strLocked: string;
  readonly infoInCat: boolean;
  readonly isOnlyImg: boolean;
  readonly isWorking: boolean;
  readonly rank: number;
}
