import { Schema } from 'mongoose';

export const TeamSchema = new Schema(
  {
    idTeam: { type: String, required: true },
    idLeague: { type: Schema.Types.ObjectId, ref: 'org' },
    idCategory: { type: Schema.Types.ObjectId, ref: 'cat' },
    idSoccerXML: String,
    idAPIfootball: String,
    intLoved: String,
    strTeam: String,
    strTeamShort: String,
    strAlternate: String,
    intFormedYear: String,
    strSport: String,
    strLeague: String,
    strLeague2: String,
    idLeague2: { type: Schema.Types.ObjectId, ref: 'org' },
    strLeague3: String,
    idLeague3: { type: Schema.Types.ObjectId, ref: 'org' },
    strLeague4: String,
    idLeague4: { type: Schema.Types.ObjectId, ref: 'org' },
    strLeague5: String,
    idLeague5: { type: Schema.Types.ObjectId, ref: 'org' },
    strLeague6: String,
    idLeague6: { type: Schema.Types.ObjectId, ref: 'org' },
    strLeague7: String,
    idLeague7: { type: Schema.Types.ObjectId, ref: 'org' },
    strDivision: String,
    strManager: String,
    strStadium: String,
    strKeywords: String,
    strRSS: String,
    strStadiumThumb: String,
    strStadiumDescription: String,
    strStadiumLocation: String,
    intStadiumCapacity: String,
    strWebsite: String,
    strFacebook: String,
    strTwitter: String,
    strInstagram: String,
    strDescriptionEN: String,
    strDescriptionDE: String,
    strDescriptionFR: String,
    strDescriptionCN: String,
    strDescriptionIT: String,
    strDescriptionJP: String,
    strDescriptionRU: String,
    strDescriptionES: String,
    strDescriptionPT: String,
    strDescriptionSE: String,
    strDescriptionNL: String,
    strDescriptionHU: String,
    strDescriptionNO: String,
    strDescriptionIL: String,
    strDescriptionPL: String,
    strGender: String,
    strCountry: String,
    strTeamBadge: String,
    strTeamJersey: String,
    strTeamLogo: String,
    strTeamFanart1: String,
    strTeamFanart2: String,
    strTeamFanart3: String,
    strTeamFanart4: String,
    strTeamBanner: String,
    strYoutube: String,
    strLocked: String,
    isOnlyImg: Boolean,
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
