import { Document } from 'mongoose';
import { BaseInterface } from '../../../shared/base.interface';

export interface IOrg extends Document, BaseInterface {
  readonly idOrg: string;
  readonly strOrg: string;
  readonly strOrgShort: string;
  readonly strOrgAlternate: string;
  categories: string[];
  readonly strSeccion: string;
  readonly idEspn: string;
  readonly idTsdb: string;
  readonly idMss: string;
  readonly idMyL: string;
  readonly idRCtrl: string;
  readonly intFormedYear: string;
  readonly strCurrentSeason: string;
  readonly strCountry: string;
  readonly strWebsite: string;
  readonly strFacebook: string;
  readonly strTwitter: string;
  readonly strYoutube: string;
  readonly strInstagram: string;
  readonly strDescriptionEN: string;
  readonly strDescriptionDE: string;
  readonly strDescriptionFR: string;
  readonly strDescriptionIT: string;
  readonly strDescriptionCN: string;
  readonly strDescriptionJP: string;
  readonly strDescriptionRU: string;
  readonly strDescriptionES: string;
  readonly strDescriptionPT: string;
  readonly strDescriptionSE: string;
  readonly strDescriptionNL: string;
  readonly strDescriptionHU: string;
  readonly strDescriptionNO: string;
  readonly strDescriptionPL: string;
  readonly strDescriptionIL: string;
  readonly strFanart1: string;
  readonly strFanart2: string;
  readonly strFanart3: string;
  readonly strFanart4: string;
  readonly strBanner: string;
  readonly strBadge: string;
  readonly strLogo: string;
  readonly strPoster: string;
  readonly strTrophy: string;
  readonly rank: number;
  readonly isWorking: boolean;
}
