import { Schema } from 'mongoose';

export const EventSchema = new Schema(
  {
    idEvent: { type: String, required: true },
    strEvent: { type: String, required: true },
    strEventAlternate: String,
    strFilename: String,
    strSport: String,
    idOrg: { type: Schema.Types.ObjectId, ref: 'Orgs', required: true },
    strLeague: String,
    categories: [{ type: Schema.Types.ObjectId, ref: 'Cats' }],
    idEspn: String,
    idTsdb: String,
    idMss: String,
    idMyL: String,
    idRCtrl: String,
    strSeason: String,
    strDescriptionEN: String,
    intRound: String,
    dateEvent: String,
    dateEventLocal: String,
    strDate: String,
    strTime: String,
    strTimeLocal: String,
    strTVStation: String,
    strResult: String,
    strCircuit: String,
    strCountry: String,
    strCity: String,
    strPoster: String,
    strFanart: String,
    strThumb: String,
    strBanner: String,
    strMap: String,
    strTweet1: String,
    strTweet2: String,
    strTweet3: String,
    strVideo: String,
    strPostponed: String,
    strLocked: String,
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
