import { Schema } from 'mongoose';

export const EventSchema = new Schema(
  {
    idEvent: { type: String, required: true, unique: true },
    strEvent: { type: String, required: true },
    strEventAlternate: { type: String, default: '' },
    strFilename: { type: String, default: '' },
    strSport: { type: String, default: '' },
    idOrg: { type: Schema.Types.ObjectId, ref: 'Orgs', required: true },
    strLeague: { type: String, default: '' },
    idCat: { type: Schema.Types.ObjectId, ref: 'Cats' },
    idEspn: { type: String, default: '' },
    idTsdb: { type: String, default: '' },
    idMss: { type: String, default: '' },
    idMyL: { type: String, default: '' },
    idRCtrl: { type: String, default: '' },
    numSeason: { type: String, default: new Date().getFullYear() },
    strSeason: { type: String, default: '' },
    strDescriptionEN: { type: String, default: '' },
    intRound: { type: String, default: '' },
    dateEvent: { type: String, default: '' },
    dateEventLocal: { type: String, default: '' },
    strDate: { type: String, default: '' },
    strTime: { type: String, default: '' },
    strTimeLocal: { type: String, default: '' },
    strTVStation: { type: String, default: '' },
    idWinner: { type: Schema.Types.ObjectId, ref: 'Drivers' },
    strResult: { type: String, default: '' },
    idCircuit: { type: Schema.Types.ObjectId, ref: 'Circuits' },
    strCircuit: { type: String, default: '' },
    strCountry: { type: String, default: '' },
    strCity: { type: String, default: '' },
    strPoster: { type: String, default: '' },
    strFanart: { type: String, default: '' },
    strThumb: { type: String, default: '' },
    strBanner: { type: String, default: '' },
    strMap: { type: String, default: '' },
    strRSS: { type: String, default: '' },
    strTweet1: { type: String, default: '' },
    strTweet2: { type: String, default: '' },
    strTweet3: { type: String, default: '' },
    strVideo: { type: String, default: '' },
    strPostponed: { type: String, default: '' },
    strLocked: { type: String, default: '' },
  },
  {
    versionKey: false,
    timestamps: true,
  },
);
